"""empty message

Revision ID: 2bf214bb8190
Revises: cd65b4082012
Create Date: 2019-09-06 11:37:01.953666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bf214bb8190'
down_revision = 'cd65b4082012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_survey_question',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('survey_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_form_id'], ['survey_form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('survey_form', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('survey_form', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('survey_form', sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSE', name='status'), nullable=False))
    op.drop_constraint('survey_form_ibfk_1', 'survey_form', type_='foreignkey')
    op.create_foreign_key(None, 'survey_form', 'user', ['owner_id'], ['id'])
    op.drop_column('survey_form', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_form', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'survey_form', type_='foreignkey')
    op.create_foreign_key('survey_form_ibfk_1', 'survey_form', 'user', ['user_id'], ['id'])
    op.drop_column('survey_form', 'status')
    op.drop_column('survey_form', 'owner_id')
    op.drop_column('survey_form', 'is_visible')
    op.drop_table('user_survey_question')
    # ### end Alembic commands ###
