"""empty message

Revision ID: 711b8f340fa2
Revises: b3356d6198e4
Create Date: 2019-09-03 15:41:32.115786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711b8f340fa2'
down_revision = 'b3356d6198e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
