"""empty message

Revision ID: 784a7524d893
Revises: fadb81f943ab
Create Date: 2019-09-22 17:03:44.065105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784a7524d893'
down_revision = 'fadb81f943ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('survey_link_link_key', 'survey_link', type_='unique')
    op.drop_column('survey_link', 'link')
    op.add_column('user', sa.Column('contact', sa.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    op.add_column('survey_link', sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('survey_link_link_key', 'survey_link', ['link'])
    # ### end Alembic commands ###
