"""empty message

Revision ID: cd65b4082012
Revises: c0496dd8c037
Create Date: 2019-09-05 21:50:13.796747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd65b4082012'
down_revision = 'c0496dd8c037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_token', sa.Column('expired_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revoked_token', 'expired_at')
    # ### end Alembic commands ###
