"""empty message

Revision ID: fadb81f943ab
Revises: 208fc1f380b4
Create Date: 2019-09-22 10:48:26.073506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadb81f943ab'
down_revision = '208fc1f380b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('survey_link_id', sa.String(length=255), nullable=True))
    op.add_column('survey_answer', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.drop_constraint('survey_answer_survey_form_id_fkey', 'survey_answer', type_='foreignkey')
    op.create_foreign_key(None, 'survey_answer', 'survey_link', ['survey_link_id'], ['id'])
    op.create_foreign_key(None, 'survey_answer', 'user', ['user_id'], ['id'])
    op.drop_column('survey_answer', 'survey_form_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('survey_form_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'survey_answer', type_='foreignkey')
    op.drop_constraint(None, 'survey_answer', type_='foreignkey')
    op.create_foreign_key('survey_answer_survey_form_id_fkey', 'survey_answer', 'survey_form', ['survey_form_id'], ['id'])
    op.drop_column('survey_answer', 'user_id')
    op.drop_column('survey_answer', 'survey_link_id')
    # ### end Alembic commands ###
